### ISSUE TITLE
Generated SSH command should contain StrictHostKeyChecking=no

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/piu#1]
Reason: EC2 instances will never be in your known_hosts file

**Comment by ePaul** [comment]
Hmm, is this the secure way to go? Shouldn't we instead have some way to authenticate those hosts?

**Comment by hjacobs** [comment]
@ePaul I assume it's ok as we only allow connections to your VPC's private network (172.31.0.0/16) and you specifically choose to connect to a certain private VPC IP (i.e. no DNS involved). Attackers could not just impersonate themselves as your target host on AWS (assuming that AWS virtual network is safe). The SSH host key would not help you anyway if the attacker compromised your host (as the SSH host key would be the same).

**Comment by ePaul** [comment]
@hjacobs Ah, I didn't read the diff and thus didn't note that this is just for the connection from odd to the final host. I guess in that case it doesn't really matter.
