### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by outime** [zalando-stups/piu#16]
Using piu would be easier if we could have a list of instances to connect to instead of finding out the IP by ourselves. Ideally, it should be a piu command that parses `senza instances` output to show a list of instances to connect, something like:

```
1) stack name (version) [instance id] - private IP
2) stack name (version) [instance id] - private IP
3) stack name (version) [instance id] - private IP
(...)
```

So you can just specify a number to connect to the specific instance.

I'm using a wrapper that does exactly this so I'm happy to write a patch to have such feature built-in if someone else likes the idea.

**Comment by szuecs** [comment]
This is a valid wish, but I think you should not couple piu to senza.
Can you think of another way how this could work without running senza?

**Comment by outime** [comment]
@szuecs sure, that won't be a problem.

**Comment by outime** [comment]
@szuecs I've some comment though. First of all, I didn't know that Senza had an option (`-p`/`--piu`) to execute Piu when listing one or more instances, so it kind of covers this feature although not completely, as you might want to just SSH a particular instance of a stack or use other Piu flags such as `--connect`. Just leaving it here in case someone didn't notice either.

Back to your suggestion, if you read [this line](https://github.com/zalando-stups/senza/blob/master/senza/cli.py#L910) you can see that it uses Piu. I was about to write this patch to then realize I'd end up copying a bunch of code from Senza into Piu which IMHO isn't very practical. At first I understood that your suggestion was fine since you might want to keep components independent of each other, but after seeing that line maybe it's not really the case. Can you clarify this?

**Comment by szuecs** [comment]
@outime As far as I understood, the missing feature in Senza is to pass piu parameters from the senza call.
I understand Senza as "Stups-Orchestrator", so it is ok to call Stups tools from there.
Piu (+Even+Odd) could be useful without Senza. To couple Piu with Senza would be wrong.

I hope I could clarify it.
Best, sandor

**Comment by outime** [comment]
@szuecs @hjacobs fair enough, I've created this PR: https://github.com/zalando-stups/piu/pull/18 let me know what do you think about the implementation. I'll write documentation about it later on.

**Comment by hjacobs** [comment]
Tests are broken: https://travis-ci.org/zalando-stups/piu

```
tests/test_cli.py::test_missing_reason PASSED
tests/test_cli.py::test_success PASSED
tests/test_cli.py::test_bad_request PASSED
tests/test_cli.py::test_auth_failure PASSED
tests/test_cli.py::test_dialog PASSED
tests/test_cli.py::test_oauth_failure PASSED
tests/test_cli.py::test_login_arg_user PASSED
tests/test_cli.py::test_login_zign_user PASSED
tests/test_cli.py::test_login_env_user PASSED
tests/test_cli.py::test_interactive_success 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by hjacobs** [comment]
Probably the test expects user input and works locally because of existing configurations.

**Comment by inikolaev** [comment]
Can someone upload updated version into PyPi?

**Comment by Raffo** [comment]
Please open a new issue for that, just to not loose track of it.
