### ISSUE TITLE
Provide access to RDS

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/piu#19]
RDS instances, when they are not public, can only be accessed from certain machines, for example, from the Odd Host. The solution is an SSH tunnel:

```
$ ssh -N -L 45432:<rds_instance_url>:<rds_port> <username>@odd.example.com
```

This makes  the RDS port be available as 45432 on the local machine.
But in order to get access to the Odd Host itself, one has to request access to some other Taupage-based machine, like:

```
$ piu <ip_address> "need to access RDS"
```

This works, but having to refer to an irrelevant Taupage-based service seems redundant.

It would be nice to have the following syntax:

```
$ piu --db <port> "need to access RDS"
```

that will just provision user's public key to the Odd Host only and print a command line for `ssh -N -L ...`

**Comment by feikesteenbergen** [comment]
👍 
However, it may be more general than just database access. Something like --vpc?

**Comment by dryewo** [comment]
One of the major benefits would be to construct the `ssh` command for the user, for that it needs to know some details about what the user wants to access.

**Comment by szuecs** [comment]
--db does not make sense to me.
I think you want to have a generic port forwarding feature.
I think you could change --connect, such that you can get the feature done.
--connect could have an optional parameter <port>.

**Comment by dryewo** [comment]
seems to be implemented already
