### ISSUE TITLE
Allow tunnel as an alternative to connect

### ISSUE THREAD

**Issue by avb1989** [zalando-stups/piu#27]
At times, we need to tunnel to the AWS instance instead of connecting to the instance.
Mostly such usecases are with datasources; used a dependency in an application one is trying to run locally, but one that you would rather not expose over internet.

piu could have an either --connect / --tunnel as options.
Something like piu user@host --tunnel localPort:remotePort .
Also will be part of the interactive access.

**Comment by mikkeloscar** [comment]
Sounds similar to #19

**Comment by avb1989** [comment]
Yes saw that issue after this :)
