### ISSUE TITLE
Change short "--user" option to uppercase "-U" to be consistent with other STUPS CLI tools

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/piu#6]
question: how come the stups tooolset cant make up its mind between -U and -u for username?

answer: good question, I think only piu uses lowercase "-u"

**Comment by hjacobs** [comment]
btw, we are using uppercase "-U" because "psql" is using that too (and we love PostgreSQL)

**Comment by tuxlife** [comment]
+1

**Comment by hjacobs** [comment]
fixed in https://github.com/zalando-stups/piu/releases/tag/0.12
