### ISSUE TITLE
Automatically run SSH command

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando-stups/piu#9]
It would be a nice time-saver if piu would had an option not only to grant access, but also to run the ssh command automatically

**Comment by hjacobs** [comment]
Do you already have a proposal on how this should work (command line options etc)?

**Comment by marek-obuchowicz** [comment]
I think that a short command name `connect` would be easy to type and meaningful:

```
piu connect <hostname> <reason>
```

(alternatively, `piu ssh <hostname> <reason>`)

Options should be the same as for request-access, with one additional option:

```
-s, --ssh-parameters     Command-line parameters to be passed to SSH
```

**Comment by hjacobs** [comment]
i.e. it would be

```
piu connect <hostname> <reason>
```

**Comment by a1exsh** [comment]
I'd vote for something like --connect (mutually exclusive with --clip).  I'm quite surprised this was not implemented: I always suspected the was some "security" reason not to do that.

Patch welcome?

**Comment by outime** [comment]
I've a submitted a PR that [enables such flag](https://github.com/zalando-stups/piu/pull/14), hope it gets accepted!

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/piu/releases/tag/1.0.11
